name: Verify dotfiles

on:
  push:
    paths:
      - "**"
  pull_request:

jobs:
  verify:
    runs-on: macos-latest

    steps:
      # 1. Check out your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Prep Homebrew
      - name: Update Homebrew
        run: brew update

      # 3. Install everything in your Brewfile
      - name: Brewfile install
        run: brew bundle install --file=Brewfile

      # 4. Verify your critical tools are available
      - name: Verify required tools
        run: |
          echo "Checking required tools..."
          command -v git >/dev/null 2>&1 || { echo "git not found"; exit 1; }
          command -v pyenv >/dev/null 2>&1 || { echo "pyenv not found"; exit 1; }
          command -v code >/dev/null 2>&1 || { echo "vscode not found"; exit 1; }
          echo "✅ All required tools are installed"

      # 5. Dry‐run your installer
      - name: Dry‐run install.sh
        env:
          DOTFILES_DIR: ${{ github.workspace }}
        run: bash install.sh

      # 6. Dry‐run your updater
      - name: Dry‐run update.sh
        run: bash update.sh
